ExaminationSystem.Presentation/Controllers/SubjectController.cs
using ExaminationSystem.Core.Features.Exams.Queries.Models;
using ExaminationSystem.Core.Features.Subject.Commands.Models;
using ExaminationSystem.Core.Features.Subject.Queries.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationSystem.Presentation.Controllers
{
    public class SubjectController : BaseController
    {
        public SubjectController(IMediator mediator) : base(mediator)
        {
        }

        [Authorize(Roles = "Teacher")]
        [Route("/TeacherSubjects")]
        //Get All Subjects For Teacher
        public IActionResult Index(string TeacherId)
        {
            var query = new GetAllSubjectsForTeacherQuery { TeacherId = TeacherId };
            var response = _Mediator.Send(query);
            if (response.Result.Succeeded)
            {
                return View(response.Result.Data);
            }
            return View();
        }
        [Authorize(Roles = "Teacher")]
        public IActionResult AddSubject()
        {
            //TempData["TeacherId"] = "123";
            return View(new AddSubjectCommand());
        }
        [Authorize(Roles = "Teacher")]
        [HttpPost]
        public IActionResult AddSubject(AddSubjectCommand subject)
        {
            subject.TeacherId = TempData["TeacherId"].ToString();
            var response = _Mediator.Send(subject);
            if (response.Result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View(subject);
        }
        [Authorize(Roles = "Teacher")]
        public IActionResult Exams(int SubjectId, string? TeacherId)
        {
            var response = _Mediator.Send(new GetAllExamsDetailsForEachSubjectQuery { SubjectId = SubjectId });
            TempData["TeacherId"] = TeacherId;
            TempData["SubjectId"] = SubjectId;
            return View(response.Result.Data);
        }

    }
}

ExaminationSystem.Presentation/Controllers/UserController.cs
using ExaminationSystem.Core.Features.User.Commands.Models;
using ExaminationSystem.Domain.Entities;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExaminationSystem.Presentation.Controllers
{
    public class UserController : BaseController
    {

        private readonly RoleManager<IdentityRole> _RoleManager;
        private readonly SignInManager<ApplicationUser> _SignInManager;

        public UserController(IMediator mediator, RoleManager<IdentityRole> roleManager, SignInManager<ApplicationUser> signInManager) : base(mediator)
        {
            _RoleManager = roleManager;
            _SignInManager = signInManager;
        }
        public async Task<IActionResult> Register()
        {
            var Roles = _RoleManager.Roles.ToList();

            var selectList = new List<SelectListItem>();
            foreach (var role in Roles)
            {
                selectList.Add(new SelectListItem(role.Name, role.Id.ToString()));
            }
            var user = new AddUserCommandDto()
            {
                Roles = selectList

            };
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Register(AddUserCommandDto UserDto)
        {
            if (ModelState.IsValid)
            {
                var role = await _RoleManager.FindByIdAsync(UserDto.RoleName);
                UserDto.RoleName = role.Name;
                var response = await _Mediator.Send(UserDto);
                if (response.Succeeded)
                {
                    return RedirectToAction("SignIn");

                }
                ViewData["Error"] = response.Message;
            }
            var Roles = _RoleManager.Roles.ToList();

            var selectList = new List<SelectListItem>();
            foreach (var role in Roles)
            {
                selectList.Add(new SelectListItem(role.Name, role.Id.ToString()));
            }
            UserDto.Roles = selectList;
            return View(UserDto);
        }
        public async Task<IActionResult> SignIn()
        {
            return View(new SignInCommandDto());
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> SignIn(SignInCommandDto userDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _Mediator.Send(userDto);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index", "Home", new { token = response.Data.ToString() });
                    //
                }
            }
            return View(userDto);
        }
        public async Task<IActionResult> SignOut()
        {
            await _SignInManager.SignOutAsync();
            return RedirectToAction("SignIn");
        }
    }
}

ExaminationSystem.Presentation/Views/Shared/_Layout.cshtml
@using ExaminationSystem.Domain.Entities
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExaminationSystem.Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExaminationSystem.Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExaminationSystem.Presentation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index" asp-route-TeacherId="@userManager.GetUserId(User)">Subjects</a>
                            </li>
                        } 
                    </ul>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="User" asp-action="SignOut">Sign Out</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExaminationSystem.Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>