ExaminationSystem.Presentation/Controllers/QuestionController.cs
using ExaminationSystem.Core.Features.Questions.Commands.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationSystem.Presentation.Controllers
{
    public class QuestionController : BaseController
    {

        #region Constructor
        public QuestionController(IMediator mediator) : base(mediator)
        {

        }

        #endregion
        #region Actions
        //public async Task<IActionResult> IndexAsync(int ExamId)
        //{
        //    var result = await _Mediator.Send(new GetAllQuestionsForExamQuery() { ExamId = ExamId });
        //    return View(result.Data);
        //}
        public IActionResult Create(int ExamId, string QuestionType)
        {
            ViewData["ExamId"] = ExamId;
            ViewData["QuestionType"] = QuestionType;
            if (QuestionType == "MCQ")
            {
                return View("CreateMCQ", new AddQuestionCommand() { QuestionType = QuestionType });
            }
            return View("CreateTOrF", new AddQuestionCommand() { QuestionType = QuestionType });
        }
        [HttpPost]
        public async Task<IActionResult> Create(AddQuestionCommand question)
        {
            if (ModelState.IsValid)
            {
                var result = _Mediator.Send(question);
                if (result.Result.Succeeded)
                {
                    if (question.QuestionType == "MCQ")
                    {
                        for (int i = 0; i < question.AnswersAndCorrect.Answers.Count; i++)
                        {
                            question.AnswersAndCorrect.Answers[i].QuestionId = result.Result.Data;
                        }
                        var answerResult = _Mediator.Send(question.AnswersAndCorrect);
                        await Console.Out.WriteLineAsync(answerResult.Result.Message);
                    }
                    RedirectToAction("ExamPaper", "Exams", new { ExamId = question.ExamId });

                }
                else
                {
                    return View($"Create{question.QuestionType}", question);
                }
            }
            return View($"Create{question.QuestionType}", question);
        }
        // var answers = questionViewModel.Answers;
        //  var resultForAddingAnswers = _Mediator.Send(answers);
        #endregion
    }

}

ExaminationSystem.Presentation/Controllers/SubjectController.cs
using ExaminationSystem.Core.Features.Exams.Queries.Models;
using ExaminationSystem.Core.Features.Subject.Commands.Models;
using ExaminationSystem.Core.Features.Subject.Queries.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationSystem.Presentation.Controllers
{
    public class SubjectController : BaseController
    {
        public SubjectController(IMediator mediator) : base(mediator)
        {
        }

        [Authorize(Roles = "Teacher")]
        [Route("/TeacherSubjects")]
        //Get All Subjects For Teacher
        public IActionResult Index(string TeacherId)
        {
            var query = new GetAllSubjectsForTeacherQuery { TeacherId = TeacherId };
            var response = _Mediator.Send(query);
            if (response.Result.Succeeded)
            {
                return View(response.Result.Data);
            }
            return View();
        }
        [Authorize(Roles = "Teacher")]
        public IActionResult AddSubject()
        {
            //TempData["TeacherId"] = "123";
            return View(new AddSubjectCommand());
        }
        [Authorize(Roles = "Teacher")]
        [HttpPost]
        public IActionResult AddSubject(AddSubjectCommand subject)
        {
            subject.TeacherId = TempData["TeacherId"].ToString();
            var response = _Mediator.Send(subject);
            if (response.Result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View(subject);
        }
        [Authorize(Roles = "Teacher")]
        public IActionResult Exams(int SubjectId, string? TeacherId)
        {
            var response = _Mediator.Send(new GetAllExamsDetailsForEachSubjectQuery { SubjectId = SubjectId });
            TempData["TeacherId"] = TeacherId;
            TempData["SubjectId"] = SubjectId;
            return View(response.Result.Data);
        }

    }
}

ExaminationSystem.Presentation/Views/Question/CreateMCQ.cshtml
@using ExaminationSystem.Core.Features.Questions.Commands.Models
@model AddQuestionCommand
@{
    ViewData["Title"] = "CreateMCQ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="row g-3" asp-action="Create" asp-controller="Question">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="col-md-4">

    <input type="hidden" asp-for="@Model.ExamId" value="@ViewData["ExamId"]" class="form-control" id="ExamId" required>
         <input type="hidden" asp-for="@Model.QuestionType" value="@Model.QuestionType" class="form-control" id="QuestionType" required>
</div>
<div class="col-md-4">
    <label asp-for="@Model.Header" for="Header" class="form-label">Header</label>
    <input type="text" asp-for="@Model.Header" class="form-control" id="Header" required>
    <span asp-validation-for="@Model.Header" class="text-danger"></span>
</div>
<div class="col-md-4">
    <label asp-for="@Model.Body" for="Body" class="form-label">Body</label>
    <input type="text" asp-for="@Model.Body" class="form-control" id="Body" required>
    <span asp-validation-for="@Model.Body" class="text-danger"></span>
</div>
<div class="col-md-4">
    <label asp-for="@Model.Mark" for="Mark" class="form-label">Mark</label>
    <input type="number" asp-for="@Model.Mark" class="form-control" id="Mark" max="1000" step="0.01" required>
    <span asp-validation-for="@Model.Mark" class="text-danger"></span>
</div>


      @for(int i=0;i<4;i++)
    {
    <div class="col-md-4">
        <label asp-for="@Model.AnswersAndCorrect.Answers[i].AnswerText" for="AnswerText" class="form-label">Answer</label>
        <input type="text" asp-for="@Model.AnswersAndCorrect.Answers[i].AnswerText" class="form-control" id="AnswerText" required>
        <span asp-validation-for="@Model.AnswersAndCorrect.Answers[i].AnswerText" class="text-danger"></span>
    </div>
    }
    <div class="col-md-4">
        <label asp-for="@Model.AnswersAndCorrect.TrueAnswer" for="TrueAnswer" class="form-label">Correct Answer</label>
    <select asp-for="@Model.AnswersAndCorrect.TrueAnswer" id="TrueAnswer">
            <option value="1">First Answer</option>
            <option value="2">Second Answer</option>
            <option value="3">Third Answer</option>
            <option value="4">Fourth Answer</option>
        </select>
    <span asp-validation-for="@Model.AnswersAndCorrect.TrueAnswer" class="text-danger"></span>
    </div>
    <div class="col-12">
        <button class="btn btn-primary" type="submit">Add</button>
        <a asp-action="Index" class="btn btn-light"> Back To List</a>
    </div>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ExaminationSystem.Presentation/Views/Question/CreateTOrF.cshtml
@using ExaminationSystem.Core.Features.Questions.Commands.Models
@model AddQuestionCommand
@{
    ViewData["Title"] = "CreateTOrF";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form  class="row g-3" asp-action="Create" asp-controller="Question">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-4">

        <input type="hidden" asp-for="@Model.ExamId" value="@ViewData["ExamId"]" class="form-control" id="ExamId" required>

    </div>
        <input type="hidden" asp-for="@Model.QuestionType" value="@Model.QuestionType" class="form-control" id="QuestionType" required>
    <div class="col-md-4">
        <label asp-for="@Model.Header" for="Header" class="form-label">Header</label>
        <input type="text" asp-for="@Model.Header" class="form-control" id="Header" required>
        <span asp-validation-for="@Model.Header" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="@Model.Body" for="Body" class="form-label">Body</label>
        <input type="text" asp-for="@Model.Body" class="form-control" id="Body" required>
        <span asp-validation-for="@Model.Body" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="@Model.Mark" for="Mark" class="form-label">Mark</label>
        <input type="number" asp-for="@Model.Mark" class="form-control" id="Mark" max="1000" step="0.01" required>
        <span asp-validation-for="@Model.Mark" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="@Model.AnswersAndCorrect.TrueAnswer" for="TrueAnswer" class="form-label">Correct Answer</label>
        <select asp-for="@Model.AnswersAndCorrect.TrueAnswer" id="TrueAnswer">
            <option value="1">True</option>
            <option value="2">False</option>
       
        </select>
        <span asp-validation-for="@Model.AnswersAndCorrect.TrueAnswer" class="text-danger"></span>
    </div>
    <div class="col-12">
        <button class="btn btn-primary" type="submit">Add</button>
        <a asp-action="Index" class="btn btn-light"> Back To List</a>
    </div>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ExaminationSystem.Presentation/Views/Question/Index.cshtml
@using ExaminationSystem.Core.Features.Questions.Queries.Dtos
@model IReadOnlyList<GetQuestionWithAnswersDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<select id="create-new-question" asp-for="@TempData["QuestionType"]">
    <option value="MCQ">MCQ</option>
    <option value="TOrF">True Or False</option>
</select>
<a class="btn btn-primary" asp-action="Create" asp-controller="Question" id="create-new-question" asp-route-ExamId="@Model[0].ExamId" asp-route-QuestionType="@TempData["QuestionType"]">Create Question</a>
@if (Model?.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(x => x[0].Body) </th>
                <th>@Html.DisplayNameFor(x => x[0].QuestionType) </th>
                <th>Answer 1 </th>
                <th>Answer 2 </th>
                <th>Answer 3 </th>
                <th>Answer 4 </th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Body</td>
                    <td>@item.QuestionType</td>
                   @for(int i = 0; i < item.Answers.Count; i++)
                    {
                    <td>@item.Answers[i] </td>    
                    } 
                  
                    <td>
                        <a class="btn btn-warning" asp-controller="Subject" asp-action="Update" asp-route-QuestionId="@item.Id">
                            <i class="fas fa-edit"></i> Update
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Subject" asp-action="Delete" asp-route-QuestionId="@item.Id">
                            <i class="fas fa-edit"></i> Delete
                        </a>
                    </td>

                </tr>
            }

        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        <h3>No Questions Found!!</h3>
    </div>
}